import type { CommodityPrice } from "./types";

/**
 * INDICATIVE sample commodity data so the Market Snapshot renders before any
 * licensed feed is connected. These are NOT live quotes — every record is
 * labelled `indicative` and carries a disclaimer. Replace by configuring a
 * provider (SGX / LME / licensed vendor) — see INTEGRATIONS.md.
 */
const now = "2026-06-25T08:00:00.000Z";

const base = {
  manualOverride: false,
  visible: true,
  timestamp: now,
  dataDelay: "indicative" as const,
};

export const mockCommodityPrices: CommodityPrice[] = [
  {
    ...base,
    id: "SICOM-TSR20",
    name: "SICOM TSR20 Rubber Futures",
    symbol: "SICOM-TSR20",
    category: "agro",
    source: "SGX / SICOM",
    exchange: "SGX",
    price: 168.5,
    currency: "USc",
    unit: "kg",
    change: 1.2,
    changePercent: 0.72,
    sourceUrl: "https://www.sgx.com/derivatives/products/natural-rubber20",
    licenseNote: "SGX/SICOM market data is licensed; indicative sample shown.",
    trend: [161, 163, 162, 165, 166, 167, 168.5],
  },
  {
    ...base,
    id: "SICOM-RSS3",
    name: "SICOM RSS3 Rubber Futures",
    symbol: "SICOM-RSS3",
    category: "agro",
    source: "SGX / SICOM",
    exchange: "SGX",
    price: 204.0,
    currency: "USc",
    unit: "kg",
    change: -0.9,
    changePercent: -0.44,
    sourceUrl: "https://www.sgx.com/derivatives/products/natural-rubber3",
    licenseNote: "SGX/SICOM market data is licensed; indicative sample shown.",
    trend: [206, 205, 207, 206, 205, 205, 204],
  },
  {
    ...base,
    id: "SNR-BENCHMARK",
    name: "Sustainable Natural Rubber (benchmark)",
    symbol: "SNR-BENCHMARK",
    category: "agro",
    source: "Indicative benchmark",
    exchange: "Indicative",
    price: null,
    currency: "USc",
    unit: "kg",
    change: null,
    changePercent: null,
    sourceUrl: "/products/natural-rubber",
    licenseNote: "No official live feed exists yet for sustainable natural rubber — placeholder benchmark.",
    trend: [],
  },
  {
    ...base,
    id: "LME-COPPER",
    name: "Copper",
    symbol: "LME-COPPER",
    category: "metals",
    source: "London Metal Exchange",
    exchange: "LME",
    price: 9620,
    currency: "USD",
    unit: "tonne",
    change: 45,
    changePercent: 0.47,
    sourceUrl: "https://www.lme.com/en/Metals/Non-ferrous/LME-Copper",
    licenseNote: "LME market data requires a licence; indicative sample shown.",
    trend: [9480, 9520, 9505, 9560, 9590, 9575, 9620],
  },
  {
    ...base,
    id: "LME-ALUMINIUM",
    name: "Aluminum",
    symbol: "LME-ALUMINIUM",
    category: "metals",
    source: "London Metal Exchange",
    exchange: "LME",
    price: 2585,
    currency: "USD",
    unit: "tonne",
    change: -12,
    changePercent: -0.46,
    sourceUrl: "https://www.lme.com/en/Metals/Non-ferrous/LME-Aluminium",
    licenseNote: "LME market data requires a licence; indicative sample shown.",
    trend: [2600, 2595, 2610, 2590, 2588, 2592, 2585],
  },
  {
    ...base,
    id: "LME-NICKEL",
    name: "Nickel",
    symbol: "LME-NICKEL",
    category: "metals",
    source: "London Metal Exchange",
    exchange: "LME",
    price: 17850,
    currency: "USD",
    unit: "tonne",
    change: 120,
    changePercent: 0.68,
    sourceUrl: "https://www.lme.com/en/Metals/Non-ferrous/LME-Nickel",
    licenseNote: "LME market data requires a licence; indicative sample shown.",
    trend: [17500, 17600, 17550, 17700, 17720, 17780, 17850],
  },
  {
    ...base,
    id: "SCRAP-COPPER",
    name: "Copper Scrap (No.1 / Millberry)",
    symbol: "SCRAP-COPPER",
    category: "circular",
    source: "Indicative recycled-metal benchmark",
    exchange: "Indicative",
    price: 8650,
    currency: "USD",
    unit: "tonne",
    change: 30,
    changePercent: 0.35,
    sourceUrl: "/products#industrial-metals",
    licenseNote: "Recycled-metal prices are indicative; connect a licensed scrap-index feed.",
    trend: [8500, 8540, 8520, 8580, 8600, 8620, 8650],
  },
  {
    ...base,
    id: "SCRAP-BUSHELLING",
    name: "Bushelling Scrap",
    symbol: "SCRAP-BUSHELLING",
    category: "circular",
    source: "Indicative recycled-metal benchmark",
    exchange: "Indicative",
    price: 415,
    currency: "USD",
    unit: "tonne",
    change: -3,
    changePercent: -0.72,
    sourceUrl: "/products#industrial-metals",
    licenseNote: "Recycled-metal prices are indicative; connect a licensed scrap-index feed.",
    trend: [420, 418, 419, 417, 416, 418, 415],
  },
  {
    ...base,
    id: "SCRAP-PNS",
    name: "PNS Scrap (Plate & Structural)",
    symbol: "SCRAP-PNS",
    category: "circular",
    source: "Indicative recycled-metal benchmark",
    exchange: "Indicative",
    price: 398,
    currency: "USD",
    unit: "tonne",
    change: 2,
    changePercent: 0.51,
    sourceUrl: "/products#industrial-metals",
    licenseNote: "Recycled-metal prices are indicative; connect a licensed scrap-index feed.",
    trend: [392, 394, 393, 395, 396, 397, 398],
  },
  {
    ...base,
    id: "MDF-PANEL",
    name: "MDF / Recycled Wood Panel",
    symbol: "MDF-PANEL",
    category: "circular",
    source: "Indicative benchmark",
    exchange: "Indicative",
    price: null,
    currency: "USD",
    unit: "m³",
    change: null,
    changePercent: null,
    sourceUrl: "/products",
    licenseNote: "No reliable public live benchmark — placeholder; update manually in admin.",
    trend: [],
  },
];
